[package]
name = "call-deno"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
deno_bindgen = "0.8.1"
deno_core = "0.306.0"
deno_runtime = "0.173.0"
tokio = { version = "1.39.2", features = ["full"] }
